Improve docker building (#500)
* Bump ruby from 2.7 to 3.0.1

Bumps ruby from 2.7 to 3.0.1.

Signed-off-by: dependabot[bot] <support@github.com>

* Bump parallel from 1.13.0 to 1.20.1 in /extension-installer

Bumps [parallel](https://github.com/grosser/parallel) from 1.13.0 to 1.20.1.
- [Release notes](https://github.com/grosser/parallel/releases)
- [Commits](https://github.com/grosser/parallel/compare/v1.13.0...v1.20.1)

Signed-off-by: dependabot[bot] <support@github.com>

* test: Simplify workflow file name

* Add support for arm64

* build: Resolve id conflict

* replace deprecated bundler parameters

* Use alpine image for ruby

Avoids https://github.com/femiwiki/docker-mediawiki/issues/502

* Split base-mediawiki stage

* Build and load for amd first

* Improve the failure step

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,6 +49,12 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
       - name: Edit configuration
         run: |
           mv configs/secret.php.example configs/secret.php;
@@ -58,18 +64,17 @@ jobs:
       - run: echo "::set-output name=version::$(date +%Y-%m-%dT%H-%M)-$(echo ${{ github.sha }} | cut -c1-8)"
         id: version
 
-      - name: Build docker image using cache
-        env:
-          DOCKER_BUILDKIT: 1
-        run: |
-          docker pull ghcr.io/femiwiki/mediawiki:latest
-          docker build \
-            --build-arg BUILDKIT_INLINE_CACHE=1 \
-            --cache-from ghcr.io/femiwiki/mediawiki:latest \
-            --tag ghcr.io/femiwiki/mediawiki:latest \
-            --tag ghcr.io/femiwiki/mediawiki:docker-test \
-            --tag ghcr.io/femiwiki/mediawiki:${{ steps.version.outputs.version }} \
-            .
+      # Build amd64 only for testing, do not push.
+      - name: Build
+        uses: docker/build-push-action@v2
+        with:
+          cache-to: type=inline
+          platforms: linux/amd64
+          load: true
+          tags: |
+            ghcr.io/femiwiki/mediawiki:latest
+            ghcr.io/femiwiki/mediawiki:docker-test
+            ghcr.io/femiwiki/mediawiki:${{ steps.version.outputs.version }}
 
       - name: Initialize docker swarm and start services
         run: |
@@ -82,29 +87,29 @@ jobs:
           echo 'Waiting for http...'
           until curl -sLfo /dev/null 127.0.0.1; do
             sleep 1; done
-
+      - name: Test Parsoid API
+        run: |
           echo 'Waiting for parsoid...'
           until [ -n "$(docker ps -qf 'name=^mediawiki_parsoid')" ]; do
             sleep 1; done
           ID="$(docker ps -qf 'name=^mediawiki_parsoid')"
           until [ "$(docker inspect "$ID" --format='{{json .State.Health.Status}}')" = \"healthy\" ]; do
             sleep 1; done
-      - name: Test Parsoid API
-        run: |
           URL="http://127.0.0.1/api.php?action=visualeditor&format=json&page=arbitrary_page&paction=parse&wikitext=arbitrary"
           [[ ! "$(curl -Ls "$URL")" = *\"error\"* ]]
+
       - name: backup of failure
         if: ${{ failure() }}
-        # Allow fails
-        shell: bash
         run: |
           echo 'Failed to connect to 127.0.0.1';
-          curl -sLo /dev/null localhost; echo $?
-          curl -Ls "$URL" http://127.0.0.1/api.php?action=visualeditor&format=json&page=arbitrary_page&paction=parse&wikitext=arbitrary
+          curl -sLo /dev/null localhost && echo "success" || echo "failure"
+          URL="http://127.0.0.1/api.php?action=visualeditor&format=json&page=arbitrary_page&paction=parse&wikitext=arbitrary"
+          curl -Ls "$URL" && echo "success" || echo "failure"
           docker ps;
           for s in $(docker service ls -q ); do docker service ps "$s"; done
           docker container ps;
           for s in $(docker service ls -q ); do docker service logs "$s"; done
+
       - name: Check if the container is still up
         run: test "$(docker service ps -qf 'desired-state=Running' -f 'desired-state=Ready' mediawiki_fastcgi)"
       - name: Try to access the mediawiki
@@ -115,12 +120,15 @@ jobs:
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
-          username: femiwiki-bot
-          password: ${{ secrets.CR_PAT }}
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Publish to Registry
-        # Publish only when in the default branch
-        if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
-        run: |
-          docker push ghcr.io/femiwiki/mediawiki:latest
-          docker push ghcr.io/femiwiki/mediawiki:${{ steps.version.outputs.version }}
+      - name: Build and push
+        uses: docker/build-push-action@v2
+        with:
+          cache-to: type=inline
+          platforms: linux/amd64,linux/arm64
+          push: ${{ github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main' }}
+          tags: |
+            ghcr.io/femiwiki/mediawiki:latest
+            ghcr.io/femiwiki/mediawiki:${{ steps.version.outputs.version }}
