Improve outputs

diff --git a/.github/workflows/docker-femiwiki.yml b/.github/workflows/docker-femiwiki.yml
--- a/.github/workflows/docker-femiwiki.yml
+++ b/.github/workflows/docker-femiwiki.yml
@@ -52,7 +52,7 @@ jobs:
           docker stack deploy -c docker-compose.yml mediawiki
 
       - name: Access 127.0.0.1:8080 until success
-        timeout-minutes: 3
+        timeout-minutes: 2
         run: |
           echo 'Waiting for http...'
           until curl -sLfo /dev/null 127.0.0.1:8080; do
@@ -72,14 +72,23 @@ jobs:
         if: ${{ failure() }}
         timeout-minutes: 1
         run: |
-          echo 'Failed to connect to 127.0.0.1:8080'
+          URL="127.0.0.1:8080"
+          curl -Lv "$URL" && echo "main success" || echo "main failure"
           URL="127.0.0.1:8080/api.php?action=visualeditor&format=json&page=arbitrary_page&paction=parse&wikitext=arbitrary"
           curl -Lv "$URL" && echo "VE success" || echo "VE failure"
           URL="127.0.0.1:8080/w/Special:MathStatus"
           curl -Lv "$URL" && echo "Math success" || echo "Math failure"
+
+      - name: backup of failure - docker status
+        if: ${{ failure() }}
+        run: |
           docker ps;
           for s in $(docker service ls -q ); do docker service ps "$s"; done
           docker container ps;
+
+      - name: backup of failure - docker logs
+        if: ${{ failure() }}
+        run: |
           for s in $(docker service ls -q ); do docker service logs "$s"; done
 
       - name: Check if the container is still up
